### ISSUE TITLE
Move cnp_excerpt from CNP-Core to module

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/Foundation-Theme#10]
Found in `cnp-core/functions/theme.php`

This function returns an automatic excerpt if one hasn't been set. Good for archive pages, not for singular pages. (Because you'd just duplicate content)

**Comment by ghost** [comment]
Done and moved to [Module-WP-Excerpt](https://github.com/Clark-Nikdel-Powell/Module-WP-Excerpt)
