### ISSUE TITLE
Move add_favicon function from CNP-Core to module

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/Foundation-Theme#12]
Found in `cnp-core/admin/General.php`

The function lets us supply different favicons based on your environment, which, if you've ever spent a lot of time editing content in WordPress, comes in handy VERY often. Now that we have staging sites for almost every site, it's good to change out the favicon based on the subdomain as well, so that you don't accidentally mistake the staging site for the live one, or vice versa. 

This little function is a tricky bastard, because it seems like we never can agree about the path to our favicon files. I'd say include a filter for the favicon url, and a filter for the environment, so that we can (potentially) have favicons for live-front-end, live-back-end, dev-front-end, dev-back-end, local-front-end, local-back-end, etc. We should have a way to supply however many different favicons we need.

**Comment by gwelser** [comment]
Trying to visualize how we want to pass in args for favicons. I'm thinking we should supply an array with a key of the `$_SERVER['HTTP_HOST']` with value of an array for public and admin (or front-end and back-end) containing the path to the ico file. If no args are passed in, we default to the following: 

```
$vars = array(
    '*' => array(
        'public' => '/img/icons/favicon.ico',
        'admin' => '/img/icons/admin-favicon.ico'
    )
);
```

Thoughts?

**Comment by jhned** [comment]
I think that's an excellent idea, let's go for it.

**Comment by gwelser** [comment]
I think this issue would be more appropriate on the CNP-Core repo.
