### ISSUE TITLE
Develop default content/settings

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/Foundation-Theme#14]
We could probably use that "Basic Settings" plugin-- or just hack it and create our own.

It'd be nice to create some default data, like a contact form, so that we're not always creating one from scratch.

**Comment by gwelser** [comment]
I guess we need to decide if this belongs in a plugin, Client Core, or the theme. If we're sticking to the precept "theme = presentation," then settings should not be part of the theme. Thoughts?

**Comment by jhned** [comment]
Yeah, my idea was that the content would be a WordPress import file. 

As for Basic Settings, the idea behind that plugin was that you turn it on, it sets the settings, then you delete it. You only need to run it once.

However, these days we have tools like the WP CLI. Not sure how robust it is, but it'd be cool if we could have some kind of configuration file to run when we first set up the site.

**Comment by gwelser** [comment]
That can most certainly be accomplished via WP CLI.

If it's alright, I'd like to look into create that process. Ideally, we would run the CLI commands in our local environment and push the db up with migrate pro. Thoughts?

**Comment by jhned** [comment]
I'd agree with that; @cnp-joe, does that sound good to you?

**Comment by gwelser** [comment]
If we're using vv create (https://github.com/bradp/vv), we can make a blueprint file that contains all the option values we want set along with plugins and themes to install.

**Comment by jhned** [comment]
I'm good with that. Does that handle WP settings as well?

**Comment by gwelser** [comment]
It does.

**Comment by ghost** [comment]
Aye, sounds good

**Comment by jhned** [comment]
Not really relevant anymore. If we end up doing this, we'll do it in Clark-Nikdel-Powell/wp-local-docker
