### ISSUE TITLE
Move post_header function from Client-Core to module

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/Foundation-Theme#6]
I still like the idea behind this function: unify the post-header markup across the site. I feel like we need to reassess the subcomponents though. Here's what it currently comes with:
- Category Bar: post category information
- Meta Bar: post date and author avatar
- Title: includes a link if not singular
- Post excerpt: includes a check for search excerpt
- Post thumbnail

If we rebuild this, it needs to be heavily filtered. Here's some of the things we'll need to filter:
- Sub-component order
- Sub-component classes / attributes
- Sub-component content
- Sub-component tags

**Comment by jhned** [comment]
Decided to ditch this function.

**Comment by gwelser** [comment]
Why ditch it? It is because of the new direction we're taking with layout/content?

**Comment by jhned** [comment]
I'm working on a Pattern Library organism to take its place. The same idea is preserved, just coded in a much better way.
