### ISSUE TITLE
Move get_p2p_connected_posts from Client-Core to module

### ISSUE THREAD

**Issue by jhned** [Clark-Nikdel-Powell/Foundation-Theme#7]
Should be a fairly quick transition. We should probably add a filter for the `$args` though, it screwed something up on Peterson Myers that I had to fix inside the function itself.

**Comment by gwelser** [comment]
Moved to modules. I didn't think a filter on the `$args` (or `$settings`, as I ended up calling them) would be necessary as they get passed in to the function. We can change this if needed, of course.
